name: Gradle Build and Shadow Jar

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Install dependencies
      run: ./gradlew --no-daemon

    - name: Build the fat jar
      run: ./gradlew shadowJar

    - name: List the contents of the jar
      run: unzip -l build/libs/gradle-example-all.jar

    - name: Run the application
      run: java -jar build/libs/gradle-example-all.jar

    - name: Publish to GitHub Packages
      run: ./gradlew publish  # Publish the artifact to GitHub Packages
      env:
        GPR_USER: ${{ secrets.GPR_USER }}  # GitHub username from secrets
        GPR_TOKEN: ${{ secrets.GPR_TOKEN }}  # GitHub token from secrets
